//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpioEntityFrameWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herramienta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Herramienta()
        {
            this.ideaHerramienta = new HashSet<ideaHerramienta>();
        }
    
        public int idHerramienta { get; set; }
        public string nombreHerramienta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ideaHerramienta> ideaHerramienta { get; set; }
    }
}
