//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpioEntityFrameWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Idea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Idea()
        {
            this.DesarrolloRegional = new HashSet<DesarrolloRegional>();
            this.ideaColor = new HashSet<ideaColor>();
            this.ideaHerramienta = new HashSet<ideaHerramienta>();
            this.ideaMiembro = new HashSet<ideaMiembro>();
        }
    
        public int idIdea { get; set; }

        [DisplayName("Nombre de la Idea")]
        public string nombreIdea { get; set; }

        [DisplayName("Inversión Requerida")]
        public double inversionRequerida { get; set; }

        [DisplayName("Objetivos Ingresos")]
        public double ingresosObjetivos { get; set; }

        [DisplayName("Inversión Infraestructura")]
        public double inversionInfraestructura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesarrolloRegional> DesarrolloRegional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [DisplayName("Idea Color")]
        public virtual ICollection<ideaColor> ideaColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [DisplayName("Idea Herramienta")]
        public virtual ICollection<ideaHerramienta> ideaHerramienta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ideaMiembro> ideaMiembro { get; set; }
    }
}
